# Generated by Django 3.2.16 on 2023-01-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20230114_0844'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['fiald_a', 'fiald_b'], name='services_su_fiald_a_15415c_idx'),
        ),
    ]
